name: construct
channels:
  - pytorch
  - nvidia
  - conda-forge 
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - opencv
  - Pillow
  - requests
  - beautifulsoup4
  - tqdm
  - pyarrow
  - h5py
  - librosa
  - numba
  - sqlalchemy
  - mysql
  - pip
  - ghostscript 

  # Pip Packages
  - pip:
      - accelerate
      - albumentations
      - bitsandbytes
      - datasets
      - einops
      - faiss-cpu
      - google-generativeai
      - googletrans==4.0.0rc1
      - huggingface-hub
      - konlpy
      - langchain
      - langchain-community 
      - langsmith
      - nltk
      - openai
      - peft
      - pdfplumber
      - pypdf
      - sentence-transformers
      - soyspacing
      - streamlit
      - tensorboard
      - tensorflow
      - tf-keras 
      - tokenizers
      - transformers
      - wandb
      - xgboost
      - camelot-py[cv]  
      - PyMuPDF         
      - frontend        